language: cpp
sudo: false

os:
  - linux
  - osx

# install more modern version of cmake on linux
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test # needed to install clang-3.9
    packages:
      - cmake
      - cmake-data
      - clang-3.9 # install a modern toolchain!

env:
  global:
    secure: ER8foFEAjEE5V/KKT76xdbaDMyqJgYopvuoUoZRhnc3W2xQ0Qp/+8qiHuS55W3PhXtRbuHW7CiiIJdDGUyhcdFa7ARBYFNmHir96nQVvRsp7cRSYf0ooK0dfkro1Qu+D4mGI7+qHLOjkSopJ2oImB9IiyR6HydMGHEoUPzWnFCQf6LweftqRv1MqB+r+BRAEjCYjclqZ0mG49YzWvUZOM3O1XWNMC3H4BJgCMnrs0Nb1gKbP6YLexl8xVVdmDShzHNkHGXl/uWsy6prCFVuMAcT6h3hRp0U+eWjdUd7jxCGzSn9vADP2Xz7Sy9kdkZ2SKPHzdjJYrxGTDtr9HWK5lIHd99OJ4rcvY+xS3bca8+0E8IezhZMXH7TsnteWv7ctz3KEr96i4EU6DQ67lmBQGqrbrj36sP0eBnYoBTlkKbpEad/61WQzCBjcDhZDdt8ShFGISAYMxZvW6BXMxy9uliunpgBlUrNpNQuNWUg+BPoFCxOQMQ75bCy1g3+nQv8+1sKYgwjfkOJY+Zf4KU9BhN7DJhFXQ6+CZTlTZbT0xlgnYGgWf+allbHGyKLx6ZuTDX96aiYzmEyPrZbCLt3Y/Rpz2BNm7O9MriUGV+rwLgo6nWipEoK1ulrML3Ug0pyrSFXFWPWAP7ogBvG6eFZttS0w2KEYrxG4EzxvwvtE2eE=
  matrix:
    - NODE_VERSION: "7.2.0"
      CMAKE_RUNTIME: "node"
      RUNTIME_VERSION: "7.2.0"
      GYP_RUNTIME: "node"
    - NODE_VERSION: "7.2.0"
      NWJS_VERSION: "0.21.0"
      CMAKE_RUNTIME: "nw"
      RUNTIME_VERSION: "0.21.0"
      GYP_RUNTIME: "node-webkit"
    - NODE_VERSION: "7.2.0"
      ELECTRON_VERTSON: "1.6.2"
      CMAKE_RUNTIME: "electron"
      RUNTIME_VERSION: "1.6.2"
      GYP_RUNTIME: "electron"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  # ensure our submodules are checked out
  - git submodule update --init --recursive
  # do we want to publish a binary?
  - PUBLISH_BINARY=false
  # if we are building a tagged commit, then yes!
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  # Set NPM to be much quieter
  - npm config set loglevel silent
  # install our build deps
  - npm install cmake-js node-pre-gyp node-pre-gyp-github nan

install:
  # add ./node_modules/.bin to path on OS X
  - if [[ "${TRAVIS_OS_NAME}" == 'osx' ]]; then export PATH=$(pwd)/node_modules/.bin:${PATH}; fi;
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' ]]; then export CXX=clang++-3.9; export CC=clang-3.9; fi; # Have linux use modern clang to compile
  - cmake-js rebuild -r=$CMAKE_RUNTIME -v=$RUNTIME_VERSION

script:
  # if we are publishing a binary, do it now
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package --runtime=$GYP_RUNTIME --target=$RUNTIME_VERSION; fi;
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp-github publish; fi;

