os: Visual Studio 2015

environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: AV/BkHKfZKFyN0t/bdgA2pCgCnwp+mdZnEj/7xVVK0wtlNYeOPYIOViLG50nCrLR

  matrix:
    - nodejs_version: "7.4.0"
      cmake_runtime: "node"
      runtime_version: "7.4.0"
      gyp_runtime: "node"
    - nodejs_version: "7.4.0"
      nwjs_version: "0.20.0"
      cmake_runtime: "nw"
      runtime_version: "0.20.0"
      gyp_runtime: "node-webkit"


platform:
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
  - ps: $env:Path += ";$(pwd)\node_modules\.bin";
  - ps: choco install winflexbison
 
  # Check if we're building the latest tag, if so
  # then we publish the binaries if tests pass.
  - ps: >
      if ($env:appveyor_repo_tag -match "true" -and ("$(git describe --tags --always HEAD)" -eq $env:appveyor_repo_tag_name)) {
        $env:publish_binary = 1;
      } else {
        $env:publish_binary = 0;
      }
      true;

  - ps: >
      if ($env:publish_binary -eq 1) {
        "We're publishing a binary!" | Write-Host
      } else {
        "We're not publishing a binary" | Write-Host
      }
      true; 
  # ensure our submodules get pulled in
  - ps: git submodule update -q --init --recursive 2>&1
  # Garbage NPM warns cause appveyor to fail.
  - ps: npm config set loglevel silent
  - ps: npm install cmake-js node-pre-gyp node-pre-gyp-github nan

build_script:
  - cmake-js rebuild -r=%cmake_runtime% -v=%runtime_version%

test_script:
  - ps: >
      if ($env:publish_binary -eq 1) {
        node-pre-gyp package --runtime=%gyp_runtime% --target=%runtime_version% 2>&1
        node-pre-gyp-github publish 2>&1
      }
      true;

deploy: OFF