os: Visual Studio 2015

environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: AV/BkHKfZKFyN0t/bdgA2pCgCnwp+mdZnEj/7xVVK0wtlNYeOPYIOViLG50nCrLR

matrix:
  # node.js
  - nodejs_version: "7.4.0"
    cmake_runtime: "node"
    runtime_version: "7.4.0"
    gyp_runtime: "node"
  # Node Webkit
  - nwjs_version: "0.20.0"
    cmake_runtime: "nw"
    runtime_version: "0.20.0"
    gyp_runtime: "node-webkit"


platform:
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
  - ps: $env:Path += ";$(pwd)\node_modules\.bin";
 
  # Check if we're building the latest tag, if so
  # then we publish the binaries if tests pass.
  - ps: >
      if ($env:appveyor_repo_tag -match "true" -and ("$(git describe --tags --always HEAD)" -eq $env:appveyor_repo_tag_name)) {
        $env:publish_binary = 1;
      } else {
        $env:publish_binary = 0;
      }
      true;

  - ps: >
      if ($env:publish_binary -eq 1) {
        "We're publishing a binary!" | Write-Host
      } else {
        "We're not publishing a binary" | Write-Host
      }
      true;
  - ps: Remove-Item .\node_modules\ -Recurse -ErrorAction Ignore
  - ps: npm install

build_script:
  - cmake-js compile -r=%CMAKE_RUNTIME% -v=%RUNTIME_VERSION%

test_script:
  - IF %PUBLISH_BINARY% == 1 (node-pre-gyp package --runtime=%GYP_RUNTIME% --target=%RUNTIME_VERSION%)
  - IF %PUBLISH_BINARY% == 1 (.\node_modules\node-pre-gyp-github\bin\node-pre-gyp-github.js publish)

deploy: OFF